backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'sitewide'
    label: 'Sitewide'
    format: 'json'
    folder: 'assets/content/sitewide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Leauge Name', name: 'name', widget: 'string' }
      - { label: 'Leauge ID', name: 'id', widget: 'string' }
      